apiVersion: skaffold/v2alpha3
kind: Config
# List out all the different config files we want to load into our cluster
deploy:
  kubectl:
    manifests:
      # Here we list out all the directories or all the files we want to sink or make use of
      - ./infra/k8s/*
build:
  # This sets that whenever we build this does not push it to docker hub, (pushing it to the docker hub is default behaviour)
  local:
    push: false
  artifacts:
    # These are going to be all the things that are going to be build
    - image: ugulzar4512/auth
      # The context or the folder that contains all the code
      context: auth
      # In the context we will find the dockerfile in the form of "Dockerfile"
      docker:
        dockerfile: Dockerfile
      # Sync is going to tell skaffold how to handle any files that change inside of your file system
      sync:
        # We're are giving manual configuration and be very explicit about what to do
        manual:
          # This is going to be set of files that skaffold needs to watch
          - src: 'src/**/*.ts'
            # The destination of DOT means where to sync this file to inside of our running container
            # The dot means basically just take whereever the file was found from and throw it to the corresponding part inside the container
            dest: .
