name: tests-payments
on:
  # only run on master
  pull_request
jobs:
  build:
    # create a virtual machine
    runs-on: ubuntu-latest
    steps:
      # take all the code of project
      - uses: actions/checkout@v2
      - run: cd payments && npm install && npm run test:ci
